### ISSUE TITLE
IP matching with a header crashes the vcc

### ISSUE THREAD

**Issue by gquintard** [varnishcache/varnish-cache#1883]
``server.ip ~ resp.http.foo`` crashe the vcl compilation

## Expected Behavior
Compilation error with error message explaining the behavior is invalid

## Current Behavior
Crash

## Steps to Reproduce (for bugs)
vtc:
```
varnishtest "Matching on an empty string"

server s1 {
	rxreq
	txresp
} -start

varnish v1 -vcl+backend {
	import std;

	sub vcl_deliver {
		if (server.ip ~ resp.http.foo) {
			set resp.http.wont = "reach";
		}
	}
} -start

client c1 {
	txreq
	rxresp
} -run
```

## Your Environment
* Version used: master
* Operating System and version: arch linux, up-to-date at the time of writing

**Comment by fgsch** [comment]
Can you paste the panic?

**Comment by gquintard** [comment]
Not sure I can, the sigsegv_handler is on, but no panic is shown.

The coredump gives me this:
```
#0  0x00007f321998f357 in ?? () from /usr/lib/varnish/libvcc.so
(gdb) bt
#0  0x00007f321998f357 in ?? () from /usr/lib/varnish/libvcc.so
#1  0x00007f321998c677 in VCC_WalkSymbols () from /usr/lib/varnish/libvcc.so
#2  0x00007f321998f5a2 in vcc_CheckReferences () from /usr/lib/varnish/libvcc.so
#3  0x00007f3219984e85 in VCC_Compile () from /usr/lib/varnish/libvcc.so
#4  0x000000000045b575 in ?? ()
#5  0x00007f3219ba63af in VSUB_run () from /usr/lib/varnish/libvarnish.so
#6  0x000000000045ba50 in mgt_VccCompile ()
#7  0x000000000045be85 in ?? ()
#8  0x000000000045c56c in mgt_vcc_startup ()
#9  0x0000000000410358 in main ()
```

**Comment by lkarsten** [comment]
Backported to 4.1 now.

No backport for 4.0, not a crash bug.
