### ISSUE TITLE
vmodtool can fail in part

### ISSUE THREAD

**Issue by lkarsten** [varnishcache/varnish-cache#1921]
Adding this here so it isn't forgotten.

vmodtool writes vcc_if.c, vcc_if.h, the man source rst and the documentation rst file.

If one of the steps fail, files are left on the file system making debugging the issue confusing.

Expected behaviour: either all the files are written correctly, or they are not written at all.

```
(=78cf1 vim:vmod_saintmode.vcc) lkarsten@IMMER ~/work/varnish-modules/src> make vcc_saintmode_if.h
/usr/share/varnish-plus/vmodtool.py -w ../docs/ -o vcc_saintmode_if ../src/vmod_saintmode.vcc
Traceback (most recent call last):
  File "/usr/share/varnish-plus/vmodtool.py", line 989, in <module>
    runmain(i_vcc, opts.rstdir, opts.output)
  File "/usr/share/varnish-plus/vmodtool.py", line 942, in runmain
    fp = open(join(rstdir, "vmod_%s%s.rst" % (vx[0].nam, suf)), "w")
IOError: [Errno 2] No such file or directory: '../docs/vmod_saintmode.rst'
Makefile:862: recipe for target 'vcc_saintmode_if.h' failed
make: *** [vcc_saintmode_if.h] Error 1
2 (=78cf1 vim:vmod_saintmode.vcc) lkarsten@IMMER ~/work/varnish-modules/src> ls -l vcc_saintmode_if.h
-rw-r--r-- 1 lkarsten lkarsten 605 april 25 10:42 vcc_saintmode_if.h
(=78cf1 vim:vmod_saintmode.vcc) lkarsten@IMMER ~/work/varnish-modules/src> cat vcc_saintmode_if.h
/*
 * NB:  This file is machine generated, DO NOT EDIT!
 *
 * Edit vmod.vcc and run make instead
 */

struct vmod_priv;

extern const struct vmod_data Vmod_saintmode_Data;

/* Object saintmode */
struct vmod_saintmode_saintmode;
VCL_VOID vmod_saintmode__init(VRT_CTX,
    struct vmod_saintmode_saintmode **, const char *, struct vmod_priv *,
    VCL_BACKEND, VCL_INT);
VCL_VOID vmod_saintmode__fini(struct vmod_saintmode_saintmode **);
VCL_BACKEND vmod_saintmode_backend(VRT_CTX,
    struct vmod_saintmode_saintmode *);

/* Functions */
VCL_VOID vmod_blacklist(VRT_CTX, struct vmod_priv *, VCL_DURATION);
(=78cf1 vim:vmod_saintmode.vcc) lkarsten@IMMER ~/work/varnish-modules/src> 
```

Running here on VCP4.1.2r1, vmodtool.py there is identical with VC4.1.2.

**Comment by lkarsten** [comment]
Giving this a couple of days to settle before backport.
