### ISSUE TITLE
SIGSEGV in vcc_checkref

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#1979]
Version is master as of now + #1978 (which has only python changes)
```
$ /tmp/sbin/varnishd -V
varnishd (varnish-trunk revision 2e1c34c)
```
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  vcc_checkref (tl=0x7f69cf0ce200, sym=0x7f69cf16f380) at vcc_xref.c:106
106			VSB_printf(tl->sb, "Undefined %s %.*s, first reference:\n",
(gdb) bt
#0  vcc_checkref (tl=0x7f69cf0ce200, sym=0x7f69cf16f380) at vcc_xref.c:106
#1  0x00007f69d11073d6 in vcc_walksymbols (tl=0x7f69cf0ce200, root=0x7f69cf0db240, func=0x7f69d110c780 <vcc_checkref>, 
    kind=SYM_NONE) at vcc_symb.c:168
#2  0x00007f69d1107440 in VCC_WalkSymbols (tl=0x7f69cf0ce200, func=0x7f69d110c780 <vcc_checkref>, kind=SYM_NONE)
    at vcc_symb.c:178
#3  0x00007f69d110c949 in vcc_CheckReferences (tl=0x7f69cf0ce200) at vcc_xref.c:124
#4  0x00007f69d10ff298 in vcc_CompileSource (tl=0x7f69cf0ce200, sp=0x7f69cf104780) at vcc_compile.c:626
#5  0x00007f69d10ff826 in VCC_Compile (tl=0x7f69cf0ce200, sb=0x7fffad967c38, 
    vclsrc=0x7f69cf0d6000 "*redacted*"..., 
    vclsrcfile=0x7fffad96a54d "./default.ela.vcl") at vcc_compile.c:714
#6  0x00000000004726a4 in run_vcc (priv=0x7fffad967dd0) at mgt/mgt_vcc.c:108
#7  0x00007f69d1531ac4 in VSUB_run (sb=0x7f69cf03a490, func=0x4724c4 <run_vcc>, priv=0x7fffad967dd0, 
    name=0x4a585a "VCC-compiler", maxlines=-1) at vsub.c:121
#8  0x0000000000472c95 in mgt_vcc_compile (vp=0x7fffad967dd0, sb=0x7f69cf03a490, C_flag=1) at mgt/mgt_vcc.c:237
#9  0x0000000000473028 in mgt_VccCompile (cli=0x7fffad969f90, vclname=0x7fffad967e60 ".CflagTest.17880", 
...
```

**Comment by nigoroll** [comment]
```
(gdb) print sym->def_b
$1 = (const struct token *) 0x0
```

**Comment by nigoroll** [comment]
backport-review: I am pretty sure this was not present before the recent vcc changes
