### ISSUE TITLE
5.0.0-beta1 segfault

### ISSUE THREAD

**Issue by lkarsten** [varnishcache/varnish-cache#2086]
5.0.0-beta1 from deb. hitch 1.4.0-beta1 in front, proxy2.

lkarsten@immer:~$ curl --http2 http://hyse.org/
curl: (52) Empty reply from server
lkarsten@immer:~$ curl --http2 http://hyse.org/
curl: (52) Empty reply from server
lkarsten@immer:~$ 

log says:
```
*   << Request  >> 19        
-   Begin          req 18 rxreq
-   Timestamp      Start: 1473677827.450968 0.000000 0.000000
-   Timestamp      Req: 1473677827.450968 0.000000 0.000000
-   Debug          "H2 upgrade attempt"
-   ReqAcct        157 0 157 0 0 0
-   End            

*   << Session  >> 18        
-   Begin          sess 0 HTTP/1
-   SessOpen       77.40.251.99 37350 :80 91.227.249.1 80 1473677827.450885 20
-   Link           req 19 rxreq
-   SessClose      REM_CLOSE 0.000
-   End            

*   << Request  >> 32777     
-   Begin          req 32776 rxreq
-   Timestamp      Start: 1473677848.272251 0.000000 0.000000
-   Timestamp      Req: 1473677848.272251 0.000000 0.000000
-   Debug          "H2 upgrade attempt"
-   ReqAcct        157 0 157 0 0 0
-   End            

*   << Session  >> 32776     
-   Begin          sess 0 HTTP/1
-   SessOpen       77.40.251.99 37352 :80 91.227.249.1 80 1473677848.272075 22
-   Link           req 32777 rxreq
-   VSL            flush
-   End            synth

Log abandoned
Log reacquired

```

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  pan_http (vsb=0x6afc80 <pan_vsb_storage>, id=<optimized out>, h=0x0) at cache/cache_panic.c:222
222	cache/cache_panic.c: No such file or directory.
[Current thread is 1 (Thread 0x7f8cd0ebf700 (LWP 23301))]
(gdb) bt full
#0  pan_http (vsb=0x6afc80 <pan_vsb_storage>, id=<optimized out>, h=0x0) at cache/cache_panic.c:222
        i = <optimized out>
        id = <optimized out>
        h = 0x0
        vsb = 0x6afc80 <pan_vsb_storage>
#1  0x0000000000435588 in pan_req (req=0x7f8cbd496020, vsb=0x6afc80 <pan_vsb_storage>) at cache/cache_panic.c:468
        stp = <optimized out>
        xp = <optimized out>
#2  pan_ic (func=0x47dc21 <__func__.9139> "SES_Close", file=<optimized out>, line=<optimized out>, cond=<optimized out>, kind=<optimized out>) at cache/cache_panic.c:638
        q = <optimized out>
        req = 0x7f8cbd496020
        bo = <optimized out>
        sa = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x0}
        err = <optimized out>
        __func__ = "pan_ic"
#3  0x000000000043cd52 in SES_Close (sp=0x7f8cbd00f420, reason=<optimized out>) at cache/cache_session.c:498
        i = <optimized out>
        __func__ = "SES_Close"
#4  0x000000000043d225 in SES_Delete (sp=sp@entry=0x7f8cbd00f420, reason=reason@entry=SC_REM_CLOSE, now=now@entry=nan(0x8000000000000)) at cache/cache_session.c:515
        __func__ = "SES_Delete"
#5  0x00000000004549ef in HTTP1_Session (wrk=wrk@entry=0x7f8cd0ebec90, req=req@entry=0x7f8cbd496020) at http1/cache_http1_fsm.c:380
        hs = HTC_S_EOF
        sp = 0x7f8cbd00f420
        st = <optimized out>
        __func__ = "HTTP1_Session"
#6  0x0000000000455217 in http1_req (wrk=0x7f8cd0ebec90, arg=0x7f8cbd496020) at http1/cache_http1_fsm.c:87
        req = 0x7f8cbd496020
        __func__ = "http1_req"
#7  0x000000000044c6d1 in Pool_Work_Thread (wrk=0x7f8cd0ebec90, pp=0x7f8cc6c0e200) at cache/cache_wrk.c:341
        tp = 0x7f8cd0ebec50
        tps = {list = {vtqe_next = 0x0, vtqe_prev = 0x0}, func = 0x436620 <pool_stat_summ>, priv = 0x7f8cc6c12600}
        i = <optimized out>
        tpx = {list = {vtqe_next = 0x0, vtqe_prev = 0x0}, func = 0x4551c0 <http1_req>, priv = 0x7f8cbd496020}
#8  WRK_Thread (qp=0x7f8cc6c0e200, stacksize=<optimized out>, thread_workspace=<optimized out>) at cache/cache_wrk.c:121
        w = 0x7f8cd0ebec90
        ww = {magic = 1670491599, pool = 0x7f8cc6c0e200, nobjhead = 0x7f8cbc4130f0, nobjcore = 0x7f8cbc40f0c0, nhashpriv = 0x7f8cbc415060, stats = {{summs = 1, sess_conn = 1, sess_drop = 0, sess_fail = 0, client_req_400 = 0, client_req_417 = 0, client_req = 1, 
              cache_hit = 0, cache_hitpass = 0, cache_miss = 0, fetch_head = 0, fetch_length = 0, fetch_chunked = 0, fetch_eof = 0, fetch_bad = 0, fetch_none = 0, fetch_1xx = 0, fetch_204 = 0, fetch_304 = 0, fetch_failed = 0, fetch_no_thread = 0, busy_sleep = 0, 
              busy_wakeup = 0, busy_killed = 0, n_object = 0, n_vampireobject = 0, n_objectcore = 0, n_objecthead = 0, s_sess = 1, s_req = 1, s_pipe = 0, s_pass = 0, s_fetch = 0, s_synth = 0, s_req_hdrbytes = 157, s_req_bodybytes = 0, s_resp_hdrbytes = 0, 
              s_resp_bodybytes = 0, sess_closed = 0, sess_readahead = 0, sess_herd = 0, hcb_nolock = 0}}, vsl = 0x0, task = {list = {vtqe_next = 0x0, vtqe_prev = 0x0}, func = 0x0, priv = 0x0}, lastused = 1473677817.4035916, v1l = 0x0, cond = {__data = {__lock = 0, 
              __futex = 16, __total_seq = 8, __wakeup_seq = 8, __woken_seq = 8, __mutex = 0x7f8cc6c181a8, __nwaiters = 0, __broadcast_seq = 0}, 
            __size = "\000\000\000\000\020\000\000\000\b\000\000\000\000\000\000\000\b\000\000\000\000\000\000\000\b\000\000\000\000\000\000\000\250\201\301ƌ\177\000\000\000\000\000\000\000\000\000", __align = 68719476736}, vcl = 0x7f8ccecde320, aws = {{
              magic = 905626964, id = "wrk", s = 0x7f8cd0ebe430 "YMK\214", f = 0x7f8cd0ebe430 "YMK\214", r = 0x0, e = 0x7f8cd0ebec28 "\025"}}, vxid_pool = {next = 32777, count = 32759}, cur_method = 257, seen_methods = 0, handling = 2, stack_start = 140242777272320, 
          stack_end = 140242777223168}
        ws = 0x7f8cd0ebe430 "YMK\214"
        u = <optimized out>
        __func__ = "WRK_Thread"

```

**Comment by fgsch** [comment]
Code points to:

```
        assert(i == 0 || errno != EBADF); /* XXX EINVAL seen */                 
```

**Comment by lkarsten** [comment]
Later crash was handled:

```
# varnishadm panic.show
Panic at: Mon, 12 Sep 2016 11:34:41 GMT
"Assert error in SES_Close(), cache/cache_session.c line 498:
  Condition(i == 0 || errno != EBADF) not true.
errno = 9 (Bad file descriptor)
thread = (cache-worker)
version = varnish-5.0.0-beta1 revision 63f94d4
ident = Linux,4.6.0-1-amd64,x86_64,-junix,-smalloc,-smalloc,-hcritbit,epoll
Backtrace:
  0x435136: varnishd() [0x435136]
  0x43cd52: varnishd(SES_Close+0x62) [0x43cd52]
  0x43d225: varnishd(SES_Delete+0x105) [0x43d225]
  0x4549ef: varnishd(HTTP1_Session+0x47f) [0x4549ef]
  0x455217: varnishd() [0x455217]
  0x44c6d1: varnishd() [0x44c6d1]
  0x44cb3b: varnishd() [0x44cb3b]
  0x7f8ccfae5444: libpthread.so.0(+0x7444) [0x7f8ccfae5444]
  0x7f8ccf82420d: libc.so.6(clone+0x6d) [0x7f8ccf82420d]
req = 0x7f8cbd496020 {
  MAGIC 0x00000000 (Should:REQ_MAGIC/0x2751aaa1)
  vxid = 0, transport = NULL
  step = 0x0,
  req_body = R_BODY_INIT,
  restarts = 0, esi_level = 0,
  ws = 0x7f8cbd4961f8 {
    MAGIC 0x00000000 (Should:WS_MAGIC/0x35fac554)
    id = \"\",
    {s, f, r, e} = {(nil), (nil), (nil), (nil)},
  },
  http[req] = (nil) {
"
```

**Comment by hermunn** [comment]
Backport review: H2 is 5.0 only, so this is not applicable.
