### ISSUE TITLE
[5.0.0] Assert error in Req_Release(), cache/cache_req.c line 123

### ISSUE THREAD

**Issue by lkarsten** [varnishcache/varnish-cache#2091]
5.0.0 from debs on stretch.

```
Panic at: Fri, 16 Sep 2016 11:12:53 GMT
"Assert error in Req_Release(), cache/cache_req.c line 123:
  Condition((req) != NULL) not true.
errno = 107 (Transport endpoint is not connected)
thread = (cache-worker)
version = varnish-5.0.0 revision 99d036f
ident = Linux,4.6.0-1-amd64,x86_64,-junix,-smalloc,-smalloc,-hcritbit,epoll
Backtrace:
  0x4351b6: varnishd() [0x4351b6]
  0x436f21: varnishd(Req_Release+0x1d1) [0x436f21]
  0x45a98c: varnishd() [0x45a98c]
  0x44cb61: varnishd() [0x44cb61]
  0x44cfcb: varnishd() [0x44cfcb]
  0x7f6ef89ce444: libpthread.so.0(+0x7444) [0x7f6ef89ce444]
  0x7f6ef870d20d: libc.so.6(clone+0x6d) [0x7f6ef870d20d]


```

backtrace from a similar crash:

```
#2  0x0000000000435314 in pan_ic (func=0x47ccd5 <__func__.8880> "Req_Release", file=<optimized out>, 
    line=<optimized out>, cond=<optimized out>, kind=<optimized out>) at cache/cache_panic.c:653
        q = <optimized out>
        req = <optimized out>
        bo = <optimized out>
        sa = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {
              0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x0}
        err = <optimized out>
        __func__ = "pan_ic"
#3  0x0000000000436f21 in Req_Release (req=0x0) at cache/cache_req.c:123
        sp = <optimized out>
        pp = <optimized out>
        __func__ = "Req_Release"
#4  0x000000000045a98c in h2_del_req (wrk=0x7f6ef9d47c90, r2=0x7f6ee6897ff8, err=<optimized out>)
    at http2/cache_http2_proto.c:219
        h2 = 0x7f6ee6888038
        sp = 0x7f6ee6c0f420
        req = <optimized out>
        r = 0
#5  0x000000000044cb61 in Pool_Work_Thread (wrk=0x7f6ef9d47c90, pp=0x7f6eefc0e100) at cache/cache_wrk.c:341
        tp = 0x7f6ef9d47c50
        tps = {list = {vtqe_next = 0x7f6ee5400000, vtqe_prev = 0x7f6ee54025e0}, func = 0x4366a0 <pool_stat_summ>, 
          priv = 0x7f6eefc12300}
        i = <optimized out>
        tpx = {list = {vtqe_next = 0x0, vtqe_prev = 0x7f6eefc0e158}, func = 0x45aa10 <h2_do_req>, 
          priv = 0x7f6ee6896020}
#6  WRK_Thread (qp=0x7f6eefc0e100, stacksize=<optimized out>, thread_workspace=<optimized out>)
    at cache/cache_wrk.c:121
        w = 0x7f6ef9d47c90
        ww = {magic = 1670491599, pool = 0x7f6eefc0e100, nobjhead = 0x7f6ee508d1d0, nobjcore = 0x0, 
          nhashpriv = 0x7f6ee502b040, stats = {{summs = 1, sess_conn = 0, sess_drop = 0, sess_fail = 0, 
              client_req_400 = 0, client_req_417 = 0, client_req = 0, cache_hit = 0, cache_hitpass = 0, 
              cache_miss = 0, fetch_head = 0, fetch_length = 0, fetch_chunked = 0, fetch_eof = 0, fetch_bad = 0, 
              fetch_none = 0, fetch_1xx = 0, fetch_204 = 0, fetch_304 = 0, fetch_failed = 0, fetch_no_thread = 0, 
              busy_sleep = 0, busy_wakeup = 0, busy_killed = 0, n_object = 0, n_vampireobject = 0, n_objectcore = 0, 
              n_objecthead = 0, s_sess = 0, s_req = 0, s_pipe = 1, s_pass = 0, s_fetch = 0, s_synth = 0, 
              s_req_hdrbytes = 0, s_req_bodybytes = 0, s_resp_hdrbytes = 0, s_resp_bodybytes = 0, sess_closed = 1, 
              sess_readahead = 0, sess_herd = 0, hcb_nolock = 0}}, vsl = 0x0, task = {list = {vtqe_next = 0x0, 
              vtqe_prev = 0x0}, func = 0x0, priv = 0x0}, lastused = 1474024373.2552848, v1l = 0x0, cond = {__data = {
              __lock = 0, __futex = 22, __total_seq = 11, __wakeup_seq = 11, __woken_seq = 11, 
              __mutex = 0x7f6eefc18068, __nwaiters = 0, __broadcast_seq = 0}, 
            __size = "\000\000\000\000\026\000\000\000\v\000\000\000\000\000\000\000\v\000\000\000\000\000\000\000\v\000\000\000\000\000\000\000h\200\301\357n\177\000\000\000\000\000\000\000\000\000", __align = 94489280512}, 
          vcl = 0x7f6ef7cb6840, aws = {{magic = 905626964, id = "wrk", s = 0x7f6ef9d47430 "\345B!/", 
              f = 0x7f6ef9d47430 "\345B!/", r = 0x0, e = 0x7f6ef9d47c28 "\025\304\066\371n\177"}}, vxid_pool = {
            next = 1245193, count = 32759}, cur_method = 5, seen_methods = 22, handling = 10, 
          stack_start = 140114614583296, stack_end = 140114614534144}
        ws = 0x7f6ef9d47430 "\345B!/"
        u = <optimized out>
        __func__ = "WRK_Thread"

```

**Comment by bsdphk** [comment]
I belive this is fixed now.

**Comment by hermunn** [comment]
Backport review: This is H2, which is not supported in Varnish Cache 4.1.
