### ISSUE TITLE
vtc terminal emulation segfault

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2638]
http://varnish-cache.org/vtest/bugs_u00011.html

```
**   top   0.6 === process p1 -log {varnishadm -n ${v1_name}} -start
**** p1    0.7 CMD: varnishadm -n /tmp/vtest.64_gcc4.7/_vtest_tmp/vtc.22761.177a128e/v1
***  p1    0.7 PID: 23079
**** p1    0.7 macro def p1_pid=23079
**** p1    0.7 macro def p1_dir=/tmp/vtest.64_gcc4.7/_vtest_tmp/vtc.22761.177a128e/p1
**** p1    0.7 macro def p1_out=/tmp/vtest.64_gcc4.7/_vtest_tmp/vtc.22761.177a128e/p1/term
**** p1    0.7 macro def p1_err=/tmp/vtest.64_gcc4.7/_vtest_tmp/vtc.22761.177a128e/p1/stderr
**   top   0.7 === process p1 -need-bytes 1
**** p1    0.7 Have 0 bytes
**** p1    0.7 stderr read 0
**** p1    0.7 stdout read 0
**   p1    0.7 WAIT4 pid=23079 status=0x008b (user 0.010000 sys 0.054000)
*    p1    0.7 Expected exit: 0x0 signal: 0 core: 0
---- p1    0.7 Bad exit status: 0x008b exit 0x0 signal 11 core 128
```

**Comment by nigoroll** [comment]
disabled coredump collection on our SmartOS vtest machine until this is fixed. Please re-enable after fix.

```
[root@varnishdev-il ~]# coreadm -d global -d global-setid
[root@varnishdev-il ~]# coreadm
     global core file pattern: /cores/core.%f.%p
     global core file content: all
       init core file pattern: core.%f.%p
       init core file content: default
            global core dumps: disabled
       per-process core dumps: disabled
      global setid core dumps: disabled
 per-process setid core dumps: disabled
     global core dump logging: disabled

```

**Comment by bsdphk** [comment]
I broke down yesterday, and imported Ed Schoutens "Teken" terminal emulation, so this ticket is strictly speaking OBE, but I'll leave it to you to close it, if that solved the problem.

**Comment by nigoroll** [comment]
I can only guess, but were you referring to #2637 ?
This one is not solved.

**Comment by nigoroll** [comment]
sorry, looks more like a bug in readline, working on it
```
Core was generated by `/home/uplex/src/varnish-cache/bin/varnishadm/.libs/varnishadm -n /tmp/vtc.54076'.
Program terminated with signal 11, Segmentation fault.
#0  0xfffffd1ca30fe06c in terminal_alloc (el=0x4244f0, t=<optimized out>, cap=0xffffffffffdfe710 <Address 0xffffffffffdfe710 out of bounds>) at terminal.c:350
350             if (cap == NULL || *cap == '\0') {
(gdb) bt
#0  0xfffffd1ca30fe06c in terminal_alloc (el=0x4244f0, t=<optimized out>, cap=0xffffffffffdfe710 <Address 0xffffffffffdfe710 out of bounds>) at terminal.c:350
#1  0xfffffd1ca30fef8b in terminal_set (el=el@entry=0x4244f0, term=<optimized out>, term@entry=0x0) at terminal.c:925
#2  0xfffffd1ca30ff2af in terminal_init (el=el@entry=0x4244f0) at terminal.c:297
#3  0xfffffd1ca30f52f6 in el_init_fd (prog=prog@entry=0xfffffd1ca3127780 <empty> "", fin=fin@entry=0x41b600 <_iob>, fout=fout@entry=0x41b680 <_iob+128>, ferr=ferr@entry=0x41b700 <_iob+256>, fdin=0, 
    fdout=fdout@entry=1, fderr=fderr@entry=2) at el.c:131
#4  0xfffffd1ca30f5423 in el_init (prog=0xfffffd1ca3127780 <empty> "", fin=0x41b600 <_iob>, fout=0x41b680 <_iob+128>, ferr=ferr@entry=0x41b700 <_iob+256>) at el.c:93
#5  0xfffffd1ca3107d18 in rl_initialize () at readline.c:296
#6  0xfffffd1ca310b141 in rl_callback_handler_install (prompt=<optimized out>, linefunc=0x404d10 <send_line>) at readline.c:2046
#7  0x0000000000404f4b in interactive (sock=<optimized out>) at varnishadm.c:250
#8  0x00000000004059dc in main (argc=<optimized out>, argv=<optimized out>) at varnishadm.c:491
```
