### ISSUE TITLE
Assert error in vca_make_session()

### ISSUE THREAD

**Issue by fgsch** [varnishcache/varnish-cache#2719]
While fuzzing I came across this panic multiple times:

```
Debug: Version: varnish-trunk revision 50d4b6f1e72b00db0211ddc9c739fb438056673f
Debug: Platform: Linux,4.9.87-linuxkit-aufs,x86_64,-jnone,-sdefault,-sdefault,-hcritbit
Debug: Child (26842) Started
Info: Child (26842) said Child starts
Error: Child (26842) died signal=6 (core dumped)
Error: Child (26842) Panic at: Sun, 24 Jun 2018 18:13:21 GMT
Assert error in vca_make_session(), cache/cache_acceptor.c line 373:
  Condition(((wa))->magic == (0x8c4b4d59)) not true.
version = varnish-trunk revision 50d4b6f1e72b00db0211ddc9c739fb438056673f, vrt api = 7.0
ident = Linux,4.9.87-linuxkit-aufs,x86_64,-jnone,-sdefault,-sdefault,-hcritbit,epoll
now = 170975.293506 (mono), 1529864000.400351 (real)
Backtrace:
  0x4adfc1: /varnish-cache/bin/varnishd/varnishd(backtrace+0x41) [0x4adfc1]
  0x85e480: /varnish-cache/bin/varnishd/varnishd() [0x85e480]
  0x85dccd: /varnish-cache/bin/varnishd/varnishd() [0x85dccd]
  0x1131ab4: /varnish-cache/bin/varnishd/varnishd(VAS_Fail+0x224) [0x1131ab4]
  0x5356ed: /varnish-cache/bin/varnishd/varnishd() [0x5356ed]
  0xad11be: /varnish-cache/bin/varnishd/varnishd() [0xad11be]
  0xac79aa: /varnish-cache/bin/varnishd/varnishd() [0xac79aa]
  0xac675a: /varnish-cache/bin/varnishd/varnishd() [0xac675a]
  0x7ffff70236ba: /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7ffff70236ba]
  0x7ffff6b4341d: /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7ffff6b4341d]
errno = 110 (Connection timed out)
thread = (cache-worker)
thr.req = (nil) {
},
thr.busyobj = (nil) {
},
```

Backtrace:
```
#0  0x00007ffff6a71428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff6a7302a in __GI_abort () at abort.c:89
#2  0x000000000085e25a in pan_ic (
    func=0x14203e0 <__func__.vca_make_session> "vca_make_session",
    file=0x141f688 "cache/cache_acceptor.c", line=373,
    cond=0x1420480 <.str> "((wa))->magic == (0x8c4b4d59)", kind=VAS_ASSERT)
    at cache/cache_panic.c:697
#3  0x0000000001131ab4 in VAS_Fail (
    func=0x14203e0 <__func__.vca_make_session> "vca_make_session",
    file=0x141f688 "cache/cache_acceptor.c", line=373,
    cond=0x1420480 <.str> "((wa))->magic == (0x8c4b4d59)", kind=VAS_ASSERT)
    at vas.c:52
#4  0x00000000005356ed in vca_make_session (wrk=0x7fffcffbc020,
    arg=0x7fffcffbc020) at cache/cache_acceptor.c:373
#5  0x0000000000ad11be in Pool_Work_Thread (pp=0x61200000ff40, wrk=0x7fffcffbc020)
    at cache/cache_wrk.c:366
#6  0x0000000000ac79aa in WRK_Thread (qp=0x61200000ff40, stacksize=94208,
    thread_workspace=2048) at cache/cache_wrk.c:120
#7  0x0000000000ac675a in pool_thread (priv=0x603000008800)
    at cache/cache_wrk.c:397
#8  0x00007ffff70236ba in start_thread (arg=0x7fffd00a0700)
    at pthread_create.c:333
#9  0x00007ffff6b4341d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

Dumping arg from # 4 above:

```
(gdb) x/x arg
0x7fffcffbc020:	0x6391adcf
```

This corresponds to the `WORKER_MAGIC`.

In Pool_Work_Thread() (https://github.com/varnishcache/varnish-cache/blob/master/bin/varnishd/cache/cache_wrk.c#L346) we set `priv` to `wrk`:

```
                        if (isnan(wrk->lastused))
                                wrk->lastused = VTIM_real();
                        wrk->task.func = NULL;
>>>>                    wrk->task.priv = wrk;
                        pp->nidle++;
                        VTAILQ_INSERT_HEAD(&pp->idle_queue, &wrk->task, list);
                        do {
                                i = Lck_CondWait(&wrk->cond, &pp->mtx,
                                    wrk->vcl == NULL ?  0 : wrk->lastused+60.);
                                if (i == ETIMEDOUT)
                                        VCL_Rel(&wrk->vcl);
                        } while (wrk->task.func == NULL);
```

under the `pp->mtx` lock.
We set vca_make_session as the func in vca_accept_task() (https://github.com/varnishcache/varnish-cache/blob/master/bin/varnishd/cache/cache_acceptor.c#L524), using Pool_Task_Arg(), which goes:

```
        Lck_Unlock(&pp->mtx);
        AZ(wrk2->task.func);

        assert(arg_len <= WS_Reserve(wrk2->aws, arg_len));
        memcpy(wrk2->aws->f, arg, arg_len);
        wrk2->task.func = func;
        wrk2->task.priv = wrk2->aws->f;
```

This happens outside the `pp->mtx` lock.

**Comment by hermunn** [comment]
Back ported dd5ea4a as 2fdd68215d6.
