### ISSUE TITLE
UB in varnishhist

### ISSUE THREAD

**Issue by fgsch** [varnishcache/varnish-cache#2773]
Building addea755c under osx with `--enable-asan --enable-ubsan`, and running `make check` leads to a failure in u00009.vtc:

```varnishhist.c:302:16: runtime error: signed integer overflow: 100 * -9223372036854775808 cannot be represented in type 'long'```

**Comment by fgsch** [comment]
And from the travis job:

```
**** p2    1.7 stderr|varnishhist.c:302:16: runtime error: signed integer overflow: 100 * -9223372036854775808 cannot be represented in type 'long'
**** p2    1.7 stderr|    #0 0x56058c421376 in accumulate /home/travis/build/varnishcache/varnish-cache/bin/varnishhist/varnishhist.c:302:16
**** p2    1.7 stderr|    #1 0x2b10ccbbeffc in vut_dispatch /home/travis/build/varnishcache/varnish-cache/lib/libvarnishapi/vut.c:105:6
**** p2    1.7 stderr|    #2 0x2b10ccb7d1da in vslq_callback /home/travis/build/varnishcache/varnish-cache/lib/libvarnishapi/vsl_dispatch.c:977:10
**** p2    1.7 stderr|    #3 0x2b10ccb56593 in vslq_process_ready /home/travis/build/varnishcache/varnish-cache/lib/libvarnishapi/vsl_dispatch.c:1299:8
**** p2    1.7 stderr|    #4 0x2b10ccb4fcc8 in VSLQ_Dispatch /home/travis/build/varnishcache/varnish-cache/lib/libvarnishapi/vsl_dispatch.c:1368:7
**** p2    1.7 stderr|    #5 0x2b10ccbbe4a8 in VUT_Main /home/travis/build/varnishcache/varnish-cache/lib/libvarnishapi/vut.c:423:7
**** p2    1.7 stderr|    #6 0x56058c41ea2e in main /home/travis/build/varnishcache/varnish-cache/bin/varnishhist/varnishhist.c:665:2
**** p2    1.7 stderr|    #7 0x2b10cde56f44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)
**** p2    1.7 stderr|    #8 0x56058c30f1eb in _start (/home/travis/build/varnishcache/varnish-cache/bin/varnishhist/.libs/lt-varnishhist+0x251eb)
**** p2    1.7 stderr|
**** p2    1.7 stderr|SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior varnishhist.c:302:16 in
```
