### ISSUE TITLE
Varnish 4.1 crash because of htc->pipeline_b == htc->pipeline_e

### ISSUE THREAD

**Issue by konstantin-f** [varnishcache/varnish-cache#3037]
Hello!

I'm running varnish 4.1 version on x86_64 machine with 24 Gb of RAM.
OS/kernel version is: Oracle Linux Server release 6.3 / 2.6.32-279.11.1.el6.x86_64

I'm got core dump during varnish working. Stack trace below:
```#0  0x0000003bb16328a5 in raise () from /lib64/libc.so.6
#1  0x0000003bb1634085 in abort () from /lib64/libc.so.6
#2  0x0000000000434b55 in pan_ic (func=0x47aff1 "v1f_read", file=0x47ada2 "http1/cache_http1_vfp.c",
    line=<value optimized out>, cond=<value optimized out>, kind=<value optimized out>) at cache/cache_panic.c:556
#3  0x00000000004548e5 in v1f_read (vc=0x2add28020a48, htc=0x2add28020a00, d=0x2adcf0b54180, len=3876)
    at http1/cache_http1_vfp.c:65
#4  0x0000000000454e08 in v1f_pull_straight (vc=0x2add28020a48, vfe=0x2add28025758, p=<value optimized out>,
    lp=0x2adcf0b54178) at http1/cache_http1_vfp.c:214
#5  0x0000000000425f50 in VFP_Suck (vc=0x2add28020a48, p=<value optimized out>, lp=0x2adcf0b54178)
    at cache/cache_fetch_proc.c:172
#6  0x00000000004368a5 in VRB_Iterate (req=0x2add280208f0, func=0x450c10 <vbf_iter_req_body>, priv=0x2add24280b60)
    at cache/cache_req_body.c:124
#7  0x0000000000450ea6 in V1F_SendReq (wrk=0x2adcf0b56c10, bo=0x2add24280b60, ctr=0x2add24280cd0, onlycached=0)
    at http1/cache_http1_fetch.c:115
#8  0x00000000004112db in vbe_dir_gethdrs (d=0x1f74638, wrk=0x2adcf0b56c10, bo=0x2add24280b60)
    at cache/cache_backend.c:212
#9  0x000000000041b4e1 in VDI_GetHdr (wrk=0x2adcf0b56c10, bo=0x2add24280b60) at cache/cache_director.c:82
#10 0x0000000000424b08 in vbf_stp_startfetch (wrk=0x2adcf0b56c10, priv=<value optimized out>)
    at cache/cache_fetch.c:285
#11 vbf_fetch_thread (wrk=0x2adcf0b56c10, priv=<value optimized out>) at ../../include/tbl/steps.h:60
#12 0x000000000044c67d in Pool_Work_Thread (qp=0x2adce80008c0, stacksize=<value optimized out>,
    thread_workspace=<value optimized out>) at cache/cache_wrk.c:372
#13 WRK_Thread (qp=0x2adce80008c0, stacksize=<value optimized out>, thread_workspace=<value optimized out>)
    at cache/cache_wrk.c:122
#14 0x000000000044cb00 in pool_thread (priv=0x2adcec007580) at cache/cache_wrk.c:403
#15 0x0000003bb1a07851 in start_thread () from /lib64/libpthread.so.0
#16 0x0000003bb16e811d in clone () from /lib64/libc.so.6
```

This one seems to happen because htc->pipeline_b == htc->pipeline_e, and they both don't equal to NULL. which means that varnish pipeline isn't filled properly.
There several home-grown vmods that can change pipeline. But all pipeline modifications in those vmods are followed by checks, that set both pipeline_e and pipeline_b to NULL if they are equal for some reason.
Thus I suppose it's most likely varnish-cache issue rather than vmods issue.

**Comment by hermunn** [comment]
Again, we need more info from you. See my comments on #3036. You can repoen that ticket or supply information here. If not, I will close this in about a week.

**Comment by nigoroll** [comment]
_about a week_ is long over
