### ISSUE TITLE
Assert error in pool_getidleworker() : Condition(((wrk)) != 0) not true.

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3192]
A panic which I do not understand straight away because I see no way how a `task->priv == NULL` could end up on the `idle_queue`.

Other things to note:

* `    temp = \221\023R,` fixed in a06095da13188d919a403fcab8c7bff8a9e61997

```
Panic at: Fri, 17 Jan 2020 16:44:28 GMT
Assert error in pool_getidleworker(), cache/cache_wrk.c line 203:
  Condition(((wrk)) != 0) not true.
version = varnish-trunk revision 4df4d2a497727a671d2f2b64d3ccd03fc4cbc3d6, vrt api = 10.0
ident = -jsolaris,-sumem,-sdefault,-hcritbit,ports
now = 54559567.752497 (mono), 1579279466.613156 (real)
Backtrace:
  45d4ab: /opt/local/sbin/varnishd'pan_ic+0x16b [0x45d4ab]
  4c74f7: /opt/local/sbin/varnishd'VAS_Fail+0x47 [0x4c74f7]
  47d115: /opt/local/sbin/varnishd'pool_getidleworker+0x135 [0x47d115]
  47dc74: /opt/local/sbin/varnishd'Pool_Task+0x74 [0x47dc74]
  44cbad: /opt/local/sbin/varnishd'VBF_Fetch+0x24d [0x44cbad]
  462848: /opt/local/sbin/varnishd'CNT_Request+0x1478 [0x462848]
  4878e4: /opt/local/sbin/varnishd'http1_req+0x5c4 [0x4878e4]
  47d43c: /opt/local/sbin/varnishd'WRK_Thread+0x24c [0x47d43c]
  47d8a8: /opt/local/sbin/varnishd'pool_thread+0x38 [0x47d8a8]
  fffffc7fef24e1ea: /lib/amd64/libc.so.1'_thrp_setup+0x8a [0xfffffc7fef24e1ea]
thread = (cache-worker)
thr.req = 4bb7800 {
  vxid = 10098887, transport = HTTP/1 {
    state = HTTP1::Proc
  }
  step = R_STP_MISS,
  req_body = R_BODY_NONE,
  restarts = 0, esi_level = 0,
  sp = 3773920 {
    fd = 83, vxid = 10098886,
    t_open = 1579279466.581912,
    t_idle = 1579279466.581912,
    ws = 3773960 {
      id = \"ses\",
      {s, f, r, e} = {37739a0, +192, 0, +344},
    },
    transport = HTTP/1 {
      state = HTTP1::Proc
    }
    client = X.X.X.X 10916 /tmp/varnish.proxy.sock,
  },
  worker = fffffc7fe87fdcc0 {
    ws = fffffc7fe87fdd48 {
      id = \"wrk\",
      {s, f, r, e} = {fffffc7fe87fd470, +0, 0, +2040},
    },
    VCL::method = MISS,
    VCL::return = fetch,
    VCL::methods = {RECV, HASH, MISS},
  },
  ws = 4bb7948 {
    id = \"req\",
    {s, f, r, e} = {4bb98a0, +312, 0, +57144},
  },
  http_conn = 4bb9820 {
    fd = 83 (@3773944),
    doclose = NULL,
    ws = 4bb7948 {
      [Already dumped, see above]
    },
    {rxbuf_b, rxbuf_e} = {4bb98a0, 4bb9957},
    {pipeline_b, pipeline_e} = {0, 0},
    content_length = -1,
    body_status = none,
    first_byte_timeout = 0.000000,
    between_bytes_timeout = 0.000000,
  },
  http[req] = 4bb79e8 {
    ws = 4bb7948 {
      [Already dumped, see above]
    },
    hdrs {
      \"GET\",
      \"/media/*REDACTED*.jpg\",
      \"HTTP/1.1\",
      \"Host: *REDACTED*\",
      \"User-Agent: *REDACTED*\",
      \"X-Forwarded-For: *REDACTED*\",
      \"X-Forwarded-Proto: https\",
      \"X-Real-Ip: *REDACTED*\",
      \"X-Varnish-Static: true\",
    },
  },
  vdc = 4bb97f8 {
    nxt = 0,
    retval = 0,
  },
  vcl = {
    name = \"boot\",
    busy = 45,
    discard = 0,
    state = auto,
    temp = \221\023R,
    conf = {
      syntax = \"41\",
      srcname = {
        \"/opt/local/etc/varnish/default.vcl\",
        \"Builtin\",
        \"/opt/local/etc/varnish/common.vcl\",
        \"/opt/local/etc/varnish/prefresh.vcl\",
      },
    },
  },
  objcore[REQ] = 4727bd0 {
    refcnt = 2,
    flags = {busy},
    exp_flags = {},
    boc = 3b368d0 {
      refcnt = 2,
      state = invalid,
      vary = 0,
      stevedore_priv = 0,
    },
    exp = {0.000000, 0.000000, 0.000000, 0.000000},
    objhead = 2d15040,
    stevedore = 0,
  },
  flags = {
  },
  privs = 4bb79d8 {
  },
  top = 4bb9880 {
    req = 4bb7800 {
      [Already dumped, see above]
    },
    privs = 4bb9898 {
    },
  },
},
thr.busyobj = 46c82e0 {
  end = 46d82c0,
  retries = 0,
  req = 4bb7800 {
    [Already dumped, see above]
  },
  sp = 3773920 {
    [Already dumped, see above]
  },
  vfc = 46ca1d8 {
    failed = 0,
    req = 0,
    resp = 0,
    wrk = 0,
    oc = 0,
    obj_flags = 0x0,
  },
  ws = 46c8320 {
    id = \"bo\",
    {s, f, r, e} = {46ca220, +0, 0, +57496},
  },
  ws_bo = 0,
  objcore[fetch] = 4727bd0 {
    [Already dumped, see above]
  },
  flags = {do_stream},
  director_req = 5d5330 {
    cli_name = boot.default,
    admin_health = healthy, changed = 1579018017.866319,
    type = backend {
      ipv4 = 127.0.0.1,
      port = 8080,
      hosthdr = 127.0.0.1,
      n_conn = 9,
    },
  },
  vcl = {
    name = \"boot\",
    busy = 45,
    discard = 0,
    state = auto,
    temp = \221\023R,
    conf = {
      syntax = \"41\",
      srcname = {
        \"/opt/local/etc/varnish/default.vcl\",
        \"Builtin\",
        \"/opt/local/etc/varnish/common.vcl\",
        \"/opt/local/etc/varnish/prefresh.vcl\",
      },
    },
  },
},
vmods = {
  blob = {6eaf70, Varnish trunk 4df4d2a497727a671d2f2b64d3ccd03fc4cbc3d6, 0.0},
  std = {6eba10, Varnish trunk 4df4d2a497727a671d2f2b64d3ccd03fc4cbc3d6, 0.0},
},
```

**Comment by nigoroll** [comment]
So I spotted a glitch, but I do not understand if it could have caused the panic.
At any rate, the respective system is now running updated code.

**Comment by nigoroll** [comment]
FYI: I made a mistake and did not update the respective system as intended. I did this morning, though.

**Comment by nigoroll** [comment]
FTR, not seen this issue again so far

**Comment by nigoroll** [comment]
FTR, this has not occurred again since b99c0bedd0990cd171a48ab883debdf5e2172d7e but I would appreciate another pair of eyes and a smart brain to process this.

**Comment by nigoroll** [comment]
I got a possibly related panic for which I got a core dump (which might be incomplete, but nevertheless):

```
Panic at: Wed, 11 Mar 2020 11:19:30 GMT
Assert error in pool_getidleworker(), cache/cache_wrk.c line 208:
  Condition((pt->func) == 0) not true.
version = varnish-trunk revision 91822c85e1717033df16fd2302ecd75fcb8b7694, vrt api = 10.0
ident = -jsolaris,-sumem,-sdefault,-hcritbit,ports
now = 59205593.668622 (mono), 1583925552.239855 (real)
Backtrace:
  45dd3b: /opt/local/sbin/varnishd'pan_ic+0x16b [0x45dd3b]
  4c9227: /opt/local/sbin/varnishd'VAS_Fail+0x47 [0x4c9227]
  47e5f3: /opt/local/sbin/varnishd'pool_getidleworker+0x1e3 [0x47e5f3]
  47f0c4: /opt/local/sbin/varnishd'Pool_Task+0x74 [0x47f0c4]
  44d40d: /opt/local/sbin/varnishd'VBF_Fetch+0x24d [0x44d40d]
  4630e8: /opt/local/sbin/varnishd'CNT_Request+0x1478 [0x4630e8]
  488e34: /opt/local/sbin/varnishd'http1_req+0x5d4 [0x488e34]
  47e888: /opt/local/sbin/varnishd'WRK_Thread+0x268 [0x47e888]
  47ecf8: /opt/local/sbin/varnishd'pool_thread+0x38 [0x47ecf8]
  fffffc7fef24e1ea: /lib/amd64/libc.so.1'_thrp_setup+0x8a [0xfffffc7fef24e1ea]
...
```

gdb:

```
Thread 412 (Thread 1650 (LWP 1650)):
#0  0xfffffc7fef25579a in _lwp_kill () from /lib/64/libc.so.1
#1  0xfffffc7fef24c07f in thr_kill () from /lib/64/libc.so.1
#2  0xfffffc7fef1e85d0 in raise () from /lib/64/libc.so.1
#3  0xfffffc7fef1c0cd8 in abort () from /lib/64/libc.so.1
#4  0x000000000045e040 in pan_ic (func=<optimized out>, file=<optimized out>, line=<optimized out>, cond=<optimized out>, 
    kind=<optimized out>) at cache/cache_panic.c:841
#5  0x00000000004c9227 in VAS_Fail (func=func@entry=0x4e7350 <__func__.7761> "pool_getidleworker", 
    file=file@entry=0x523a2d "cache/cache_wrk.c", line=line@entry=208, cond=cond@entry=0x523ab8 "(pt->func) == 0", 
    kind=kind@entry=VAS_ASSERT) at vas.c:53
#6  0x000000000047e5f3 in pool_getidleworker (pp=pp@entry=0x7f17b0, prio=prio@entry=TASK_QUEUE_BO) at cache/cache_wrk.c:208
#7  0x000000000047f0c4 in Pool_Task (pp=0x7f17b0, task=0x55625d8, prio=prio@entry=TASK_QUEUE_BO) at cache/cache_wrk.c:288
#8  0x000000000044d40d in VBF_Fetch (wrk=wrk@entry=0xfffffc7fe84adcc0, req=req@entry=0x39e9fc0, oc=0x38390d0, oldoc=0x0, 
    mode=mode@entry=VBF_NORMAL) at cache/cache_fetch.c:1079
#9  0x00000000004630e8 in cnt_miss (req=0x39e9fc0, wrk=0xfffffc7fe84adcc0) at cache/cache_req_fsm.c:630
#10 CNT_Request (req=req@entry=0x39e9fc0) at ../../include/tbl/steps.h:43
#11 0x0000000000488e34 in HTTP1_Session (req=0x39e9fc0, wrk=0xfffffc7fe84adcc0) at http1/cache_http1_fsm.c:427
#12 http1_req (wrk=0xfffffc7fe84adcc0, arg=0x39e9fc0) at http1/cache_http1_fsm.c:88
#13 0x000000000047e888 in Pool_Work_Thread (wrk=0xfffffc7fe84adcc0, pp=0x7f17b0) at cache/cache_wrk.c:414
#14 WRK_Thread (qp=0x7f17b0, stacksize=<optimized out>, thread_workspace=<optimized out>) at cache/cache_wrk.c:148
#15 0x000000000047ecf8 in pool_thread (priv=0x76fa80) at cache/cache_wrk.c:447
#16 0xfffffc7fef24e1ea in _thrp_setup () from /lib/64/libc.so.1
#17 0xfffffc7fef24e500 in ?? () from /lib/64/libc.so.1
#18 0x0000000000000000 in ?? ()

(gdb) print *pp
$2 = {magic = 1617320186, list = {vtqe_next = 0x873480, vtqe_prev = 0x6edfe8}, poolsocks = {vtqh_first = 0x8733c0, 
    vtqh_last = 0x873428}, die = 0, herder_cond = {__pthread_cond_flags = {__pthread_cond_flag = "\000\003\001", 
      __pthread_cond_type = 0, __pthread_cond_magic = 17238}, __pthread_cond_data = 0}, herder_thr = 115, mtx = {priv = 0x54e850}, 
  nidle = 27, idle_queue = {vtqh_first = 0xfffffc7fe6a2dcf8, vtqh_last = 0xfffffc7fe844dcf8}, queues = {{vtqh_first = 0x0, 
      vtqh_last = 0x7f1818}, {vtqh_first = 0x0, vtqh_last = 0x7f1828}, {vtqh_first = 0x0, vtqh_last = 0x7f1838}, {vtqh_first = 0x0, 
      vtqh_last = 0x7f1848}, {vtqh_first = 0x0, vtqh_last = 0x7f1858}}, nthr = 50, lqueue = 0, sdropped = 0, rdropped = 0, 
  nqueued = 0, ndequeued = 18446744073709550643, a_stat = 0x7f1aa0, b_stat = 0x7f18d0, mpl_req = 0x7f2db0, mpl_sess = 0x7f2f70, 
  waiter = 0x7f32a0}

(gdb) print *(struct pool_task *)0xfffffc7fe6a2dcf8
$4 = {list = {vtqe_next = 0x6f5bde0f7fb07ace, vtqe_prev = 0x7f1808}, func = 0x161d175e21460300, priv = 0x65a1f09bb13d9ab9}

```

In my mind, this smells like memory corruption.

Interestingly, on the same system, I see other really weird panics, which also point in that direction:

```
Panic at: Thu, 05 Mar 2020 18:07:33 GMT
Wrong turn at cache/cache_main.c:287:
Signal 11 (Segmentation Fault) received at fffffc7e25ec3000 si_code 2
version = varnish-trunk revision 91822c85e1717033df16fd2302ecd75fcb8b7694, vrt api = 10.0
ident = -jsolaris,-sumem,-sdefault,-hcritbit,ports
now = 58711680.555562 (mono), 1583431632.769509 (real)
Backtrace:
  45dd3b: /opt/local/sbin/varnishd'pan_ic+0x16b [0x45dd3b]
  4c9227: /opt/local/sbin/varnishd'VAS_Fail+0x47 [0x4c9227]
  4591a9: /opt/local/sbin/varnishd'child_signal_handler+0x109 [0x4591a9]
  fffffc7fef24e5c6: /lib/amd64/libc.so.1'__sighndlr+0x6 [0xfffffc7fef24e5c6]
  fffffc7fef2411db: /lib/amd64/libc.so.1'call_user_handler+0x1db [0xfffffc7fef2411db]
  fffffc7fef1ac58f: /lib/amd64/libc.so.1'memcpy+0xa0f [0xfffffc7fef1ac58f]
  48c34a: /opt/local/sbin/varnishd'v1f_pull_straight+0x8a [0x48c34a]
  44df70: /opt/local/sbin/varnishd'VFP_Suck+0x90 [0x44df70]
  44f7ba: /opt/local/sbin/varnishd'vfp_testgunzip_pull+0x7a [0x44f7ba]
  44df70: /opt/local/sbin/varnishd'VFP_Suck+0x90 [0x44df70]
```

```
Panic at: Fri, 13 Mar 2020 10:39:54 GMT
Wrong turn at cache/cache_main.c:287:
Signal 11 (Segmentation Fault) received at fffffc7fef24e558 si_code 1
version = varnish-trunk revision 91822c85e1717033df16fd2302ecd75fcb8b7694, vrt api = 10.0
ident = -jsolaris,-sumem,-sdefault,-hcritbit,ports
now = 59376024.812997 (mono), 1584095985.583431 (real)
Backtrace:
  45dd3b: /opt/local/sbin/varnishd'pan_ic+0x16b [0x45dd3b]
  4c9227: /opt/local/sbin/varnishd'VAS_Fail+0x47 [0x4c9227]
  4591a9: /opt/local/sbin/varnishd'child_signal_handler+0x109 [0x4591a9]
  fffffc7fef24e5c6: /lib/amd64/libc.so.1'__sighndlr+0x6 [0xfffffc7fef24e5c6]
  fffffc7fef2411db: /lib/amd64/libc.so.1'call_user_handler+0x1db [0xfffffc7fef2411db]
  fffffc7fef24e558: /lib/amd64/libc.so.1'__lwp_park+0x28 [0xfffffc7fef24e558]
  5fded692a3b6bd5f: [0x5fded692a3b6bd5f]
thread = (cache-worker)
thr.req = 0 {
},
...
  worker = fffffc7fe61bdcc0 {
    MAGIC at fffffc7fe61bdcc0 is 0x34fcdde5 (Should be: WORKER_MAGIC/0x6391adcf)
    ws = fffffc7fe61bdd48 {
      MAGIC at fffffc7fe61bdd48 is 0xf9d60094 (Should be: WS_MAGIC/0x35fac554)
      id = \"?\335\243\346\376&f\377\",
      {s, f, r, e} = {75867a00ff6626fe, ff42bd7ff7b96f, +8723892281148474744, +6363156005229843671},
    },
```

```
Panic at: Tue, 17 Mar 2020 08:54:41 GMT
Wrong turn at cache/cache_main.c:287:
Signal 11 (Segmentation Fault) received at fffffc7e109ef898 si_code 2
version = varnish-trunk revision 91822c85e1717033df16fd2302ecd75fcb8b7694, vrt api = 10.0
ident = -jsolaris,-sumem,-sdefault,-hcritbit,ports
now = 59715299.587364 (mono), 1584435264.721051 (real)
Backtrace:
  45dd3b: /opt/local/sbin/varnishd'pan_ic+0x16b [0x45dd3b]
  4c9227: /opt/local/sbin/varnishd'VAS_Fail+0x47 [0x4c9227]
  4591a9: /opt/local/sbin/varnishd'child_signal_handler+0x109 [0x4591a9]
  fffffc7fef24e5c6: /lib/amd64/libc.so.1'__sighndlr+0x6 [0xfffffc7fef24e5c6]
  fffffc7fef2411db: /lib/amd64/libc.so.1'call_user_handler+0x1db [0xfffffc7fef2411db]
  fffffc7fe8e5de42: /lib/amd64/libumem.so.1'umem_cache_alloc+0x92 [0xfffffc7fe8e5de42]
  4ae55e: /opt/local/sbin/varnishd'smu_alloc+0xbe [0x4ae55e]
  4adfb8: /opt/local/sbin/varnishd'SML_allocobj+0x88 [0x4adfb8]
  4a8d66: /opt/local/sbin/varnishd'STV_NewObject+0x76 [0x4a8d66]
  44a714: /opt/local/sbin/varnishd'vbf_beresp2obj+0xe4 [0x44a714]
```

I am working on it, sharing this intermediate state in case anyone has helpful ideas.

**Comment by nigoroll** [comment]
Have not seen ever again, and no handle on it anyway.
