### ISSUE TITLE
r02702 panic on alpine via cci

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3492]
CCI shows an interesting failure, unfortunately, the panic output is not exactly helpful

```

FAIL: tests/r02702
==================

**** dT    0.000
*    top   TEST ../../../bin/varnishtest/tests/r02702.vtc starting
**** top   extmacro def pwd=/workspace/varnish-20210111/_build/bin/varnishtest
**** top   extmacro def localhost=127.0.0.1
**** top   extmacro def bad_backend=127.0.0.1:34967
**** top   extmacro def listen_addr=127.0.0.1:0
**** top   extmacro def bad_ip=192.0.2.255
**** top   extmacro def topbuild=/workspace/varnish-20210111/_build
**** top   macro def testdir=/workspace/varnish-20210111/_build/bin/varnishtest/../../../bin/varnishtest/tests
**** top   macro def tmpdir=/tmp/vtc.35033.1b573e86
**   top   === varnishtest "probes to UDS backends with .proxy_header in [1...
*    top   VTEST probes to UDS backends with .proxy_header in [12]
**   top   === server s1 -listen "${tmpdir}/s1.sock" {
**   s1    Starting server
**** dT    0.001
**** s1    macro def s1_addr=0.0.0.0
**** s1    macro def s1_port=0
**** s1    macro def s1_sock=/tmp/vtc.35033.1b573e86/s1.sock
*    s1    Listen on /tmp/vtc.35033.1b573e86/s1.sock
**   top   === varnish v1 -vcl {
**   s1    Started on /tmp/vtc.35033.1b573e86/s1.sock (1 iterations)
**** dT    0.003
**   v1    Launch
***  v1    CMD: cd ${pwd} && exec varnishd  -d -n /tmp/vtc.35033.1b573e86/v1 -l 2m -p auto_restart=off -p syslog_cli_traffic=off -p thread_pool_min=10 -p debug=+vtc_mode -p vsl_mask=+Debug -p h2_initial_window_size=1m -p h2_rx_window_low_water=64k -a '127.0.0.1:0' -M '127.0.0.1 42997' -P /tmp/vtc.35033.1b573e86/v1/varnishd.pid -p vmod_path=/workspace/varnish-20210111/_build/vmod/.libs 
***  v1    CMD: cd /workspace/varnish-20210111/_build/bin/varnishtest && exec varnishd  -d -n /tmp/vtc.35033.1b573e86/v1 -l 2m -p auto_restart=off -p syslog_cli_traffic=off -p thread_pool_min=10 -p debug=+vtc_mode -p vsl_mask=+Debug -p h2_initial_window_size=1m -p h2_rx_window_low_water=64k -a '127.0.0.1:0' -M '127.0.0.1 42997' -P /tmp/vtc.35033.1b573e86/v1/varnishd.pid -p vmod_path=/workspace/varnish-20210111/_build/vmod/.libs 
***  v1    PID: 35061
**** v1    macro def v1_pid=35061
**** v1    macro def v1_name=/tmp/vtc.35033.1b573e86/v1
**** dT    0.012
***  v1    debug|Debug: Version: varnish-20210111 revision e75a5d70ce7a6d13a32ac616770d593e6f237015
***  v1    debug|Debug: Platform: Linux,4.15.0-1077-aws,x86_64,-jnone,-sdefault,-sdefault,-hcritbit
***  v1    debug|200 319     
***  v1    debug|-----------------------------
***  v1    debug|Varnish Cache CLI 1.0
***  v1    debug|-----------------------------
***  v1    debug|Linux,4.15.0-1077-aws,x86_64,-jnone,-sdefault,-sdefault,-hcritbit
***  v1    debug|varnish-20210111 revision e75a5d70ce7a6d13a32ac616770d593e6f237015
***  v1    debug|
***  v1    debug|Type 'help' for command list.
***  v1    debug|Type 'quit' to close CLI session.
***  v1    debug|Type 'start' to launch worker process.
***  v1    debug|
**** dT    0.110
**** v1    CLIPOLL 1 0x1 0x0
***  v1    CLI connection fd = 7
**** dT    0.111
***  v1    CLI RX  107
**** v1    CLI RX|obxdszdihoubphgyynpnufepjkgliuzb
**** v1    CLI RX|
**** v1    CLI RX|Authentication required.
**** v1    CLI TX|auth c58ca62147244dfa74059bfd9c96f01a6b069bd664bfcbb27249712834e1a95d
***  v1    CLI RX  200
**** v1    CLI RX|-----------------------------
**** v1    CLI RX|Varnish Cache CLI 1.0
**** v1    CLI RX|-----------------------------
**** v1    CLI RX|Linux,4.15.0-1077-aws,x86_64,-jnone,-sdefault,-sdefault,-hcritbit
**** v1    CLI RX|varnish-20210111 revision e75a5d70ce7a6d13a32ac616770d593e6f237015
**** v1    CLI RX|
**** v1    CLI RX|Type 'help' for command list.
**** v1    CLI RX|Type 'quit' to close CLI session.
**** v1    CLI RX|Type 'start' to launch worker process.
**** v1    CLI TX|vcl.inline vcl1 << %XJEIFLH|)Xspa8P
**** v1    CLI TX|vcl 4.1;
**** v1    CLI TX|
**** v1    CLI TX|\tbackend s1 {
**** v1    CLI TX|\t\t.path = "/tmp/vtc.35033.1b573e86/s1.sock";
**** v1    CLI TX|\t\t.proxy_header = 1;
**** v1    CLI TX|
**** v1    CLI TX|\t\t.probe = {
**** v1    CLI TX|\t\t\t.window = 1;
**** v1    CLI TX|\t\t\t.threshold = 1;
**** v1    CLI TX|\t\t\t.interval = 0.5s;
**** v1    CLI TX|\t\t}
**** v1    CLI TX|\t}
**** v1    CLI TX|
**** v1    CLI TX|%XJEIFLH|)Xspa8P
**** dT    0.212
***  v1    vsl|No VSL chunk found (child not started ?)
**** dT    0.312
***  v1    vsl|No VSL chunk found (child not started ?)
**** dT    0.331
***  v1    CLI RX  200
**** v1    CLI RX|VCL compiled.
**** v1    CLI TX|vcl.use vcl1
***  v1    CLI RX  200
**   v1    Start
**** v1    CLI TX|start
**** dT    0.376
***  v1    debug|Debug: Child (35155) Started
**** dT    0.409
***  s1    accepted fd 5 0.0.0.0 0
**   s1    === rxreq
***  v1    CLI RX  200
***  v1    wait-running
**** v1    CLI TX|status
***  v1    debug|Info: Child (35155) said Child starts
**** dT    0.411
**** s1    rxhdrlen = 0
---- s1    HTTP header is incomplete
**** dT    0.412
**** v1    vsl|          0 CLI             - Rd vcl.load "vcl1" vcl_vcl1.1610355659.131757/vgc.so 1auto
**** v1    vsl|          0 Backend_health  - s1 Went sick -------- 0 1 1 0.000000 0.000000 ""
**** v1    vsl|          0 Backend_health  - s1 Still sick -------- 0 1 1 0.000000 0.000000 ""
**** v1    vsl|          0 CLI             - Wr 200 52 Loaded "vcl_vcl1.1610355659.131757/vgc.so" as "vcl1"
**** v1    vsl|          0 CLI             - Rd vcl.use "vcl1"
**** v1    vsl|          0 CLI             - Wr 200 0 
**** v1    vsl|          0 CLI             - Rd start
**** v1    vsl|          0 CLI             - Wr 200 0 
**** dT    1.411
***  v1    debug|Error: Child (35155) died signal=6
***  v1    debug|Error: Child (35155) Panic at: Mon, 11 Jan 2021 09:01:00 GMT
***  v1    debug|Wrong turn at ../../../bin/varnishd/cache/cache_main.c:287:
***  v1    debug|Signal 11 (Segmentation fault) received at 0 si_code 1
***  v1    debug|version = varnish-20210111 revision e75a5d70ce7a6d13a32ac616770d593e6f237015, vrt api = 13.0
***  v1    debug|ident = Linux,4.15.0-1077-aws,x86_64,-jnone,-sdefault,-sdefault,-hcritbit,epoll
***  v1    debug|now = 32162.435728 (mono), 1610355659.429163 (real)
***  v1    debug|Backtrace:
***  v1    debug|  ip=0x55dd2a88a853, sp=0x7f2209a61d10 <pan_ic+0x2bc>
***  v1    debug|  ip=0x55dd2a920d87, sp=0x7f2209a61e10 <VAS_Fail+0x59>
***  v1    debug|  ip=0x55dd2a883bee, sp=0x7f2209a61e50 <child_signal_handler+0x265>
***  v1    debug|  ip=0x7f2209bd5304, sp=0x7f2209a62380 <sigwaitinfo+0x8>
***  v1    debug|argv = {
***  v1    debug|  [0] = \"varnishd\",
***  v1    debug|  [1] = \"-d\",
***  v1    debug|  [2] = \"-n\",
***  v1    debug|  [3] = \"/tmp/vtc.35033.1b573e86/v1\",
***  v1    debug|  [4] = \"-l\",
***  v1    debug|  [5] = \"2m\",
***  v1    debug|  [6] = \"-p\",
***  v1    debug|  [7] = \"auto_restart=off\",
***  v1    debug|  [8] = \"-p\",
***  v1    debug|  [9] = \"syslog_cli_traffic=off\",
***  v1    debug|  [10] = \"-p\",
***  v1    debug|  [11] = \"thread_pool_min=10\",
***  v1    debug|  [12] = \"-p\",
***  v1    debug|  [13] = \"debug=+vtc_mode\",
***  v1    debug|  [14] = \"-p\",
***  v1    debug|  [15] = \"vsl_mask=+Debug\",
***  v1    debug|  [16] = \"-p\",
***  v1    debug|  [17] = \"h2_initial_window_size=1m\",
***  v1    debug|  [18] = \"-p\",
***  v1    debug|  [19] = \"h2_rx_window_low_water=64k\",
***  v1    debug|  [20] = \"-a\",
***  v1    debug|  [21] = \"127.0.0.1:0\",
***  v1    debug|  [22] = \"-M\",
***  v1    debug|  [23] = \"127.0.0.1 42997\",
***  v1    debug|  [24] = \"-P\",
***  v1    debug|  [25] = \"/tmp/vtc.35033.1b573e86/v1/varnishd.pid\",
***  v1    debug|  [26] = \"-p\",
***  v1    debug|  [27] = \"vmod_path=/workspace/varnish-20210111/_build/vmod/.libs\",
***  v1    debug|}
***  v1    debug|pthread.self = 0x7f22096e1b20
***  v1    debug|pthread.name = (cache-worker)
***  v1    debug|pthread.attr = {
***  v1    debug|  guard = 8192,
***  v1    debug|  stack_bottom = 0x7f22096d3000,
***  v1    debug|  stack_top = 0x7f22096e1af0,
***  v1    debug|  stack_size = 60144,
***  v1    debug|}
***  v1    debug|thr.req = NULL
***  v1    debug|thr.busyobj = NULL
***  v1    debug|vmods = {
***  v1    debug|},
***  v1    debug|pools = {
***  v1    debug|  pool = 0x55dd2b71ab80 {
***  v1    debug|    nidle = 9,
***  v1    debug|    nthr = 10,
***  v1    debug|    lqueue = 0
***  v1    debug|  },
***  v1    debug|  pool = 0x55dd2b719b80 {
***  v1    debug|    nidle = 8,
***  v1    debug|    nthr = 10,
***  v1    debug|    lqueue = 0
***  v1    debug|  },
***  v1    debug|},
***  v1    debug|
***  v1    debug|
**** dT    1.430
***  v1    debug|Debug: Child cleanup complete
***  v1    CLI RX  200
**** v1    CLI RX|Child in state stopped
---- v1    Child stopped before running: 200 Child in state stopped
*    top   RESETTING after ../../../bin/varnishtest/tests/r02702.vtc
**   s1    Waiting for server (4/-1)
**   v1    Wait
**** v1    CLI TX|panic.clear
***  v1    CLI RX  200
---- v1    Unexpected panic
*    top   failure during reset
#    top  TEST ../../../bin/varnishtest/tests/r02702.vtc FAILED (1.432) exit=2
```

**Comment by nigoroll** [comment]
with `sigsegv_handler=off`:

```
Core was generated by `varnishd -d -n /tmp/vtc.23498.7a297e9e/v1 -p debug=+vcl_keep -p debug=+vmod_so_'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f047d3dd49d in getnameinfo () from /lib/ld-musl-x86_64.so.1
[Current thread is 1 (LWP 23534)]
(gdb) bt
#0  0x00007f047d3dd49d in getnameinfo () from /lib/ld-musl-x86_64.so.1
#1  0x0000000000000000 in ?? ()
```
