### ISSUE TITLE
-in- finite panic loop

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3764]
I just saw this, likely fallout from #3688

```
Core was generated by `/tmp/sbin/varnishd -a 127.0.0.1:8080 -n /tmp/t -f /home/slink/Devel/varnish-git'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  pan_ic (func=0x55d8be "pan_ic", file=0x55d76e "cache/cache_panic.c", line=723, cond=0x55d8c5 "(pthread_mutex_lock(&panicstr_mtx)) == 0", kind=VAS_ASSERT) at cache/cache_panic.c:721
721		int err = errno;
[Current thread is 1 (Thread 0x7f1249e0f700 (LWP 88805))]
(gdb) bt
#0  pan_ic (func=0x55d8be "pan_ic", file=0x55d76e "cache/cache_panic.c", line=723, 
    cond=0x55d8c5 "(pthread_mutex_lock(&panicstr_mtx)) == 0", kind=VAS_ASSERT) at cache/cache_panic.c:721
#1  0x000000000052b595 in VAS_Fail (func=0x55d8be "pan_ic", file=0x55d76e "cache/cache_panic.c", line=723, 
    cond=0x55d8c5 "(pthread_mutex_lock(&panicstr_mtx)) == 0", kind=VAS_ASSERT) at vas.c:67
#2  0x000000000045ebb6 in pan_ic (func=0x55d8be "pan_ic", file=0x55d76e "cache/cache_panic.c", line=723, 
    cond=0x55d8c5 "(pthread_mutex_lock(&panicstr_mtx)) == 0", kind=VAS_ASSERT) at cache/cache_panic.c:723
#3  0x000000000052b595 in VAS_Fail (func=0x55d8be "pan_ic", file=0x55d76e "cache/cache_panic.c", line=723, 
    cond=0x55d8c5 "(pthread_mutex_lock(&panicstr_mtx)) == 0", kind=VAS_ASSERT) at vas.c:67
#4  0x000000000045ebb6 in pan_ic (func=0x55d8be "pan_ic", file=0x55d76e "cache/cache_panic.c", line=723, 
    cond=0x55d8c5 "(pthread_mutex_lock(&panicstr_mtx)) == 0", kind=VAS_ASSERT) at cache/cache_panic.c:723
#5  0x000000000052b595 in VAS_Fail (func=0x55d8be "pan_ic", file=0x55d76e "cache/cache_panic.c", line=723, 
...
#341 0x000000000052b595 in VAS_Fail (func=0x55d8be "pan_ic", file=0x55d76e "cache/cache_panic.c", line=723, 
    cond=0x55d8c5 "(pthread_mutex_lock(&panicstr_mtx)) == 0", kind=VAS_ASSERT) at vas.c:67
#342 0x000000000045ebb6 in pan_ic (func=0x0, file=0x0, line=0, cond=0x0, kind=VAS_WRONG)
    at cache/cache_panic.c:723
#343 0x0000000000000000 in ?? ()
(gdb) p errno
$1 = 0
```

**Comment by nigoroll** [comment]
Technically, the title was incorrect, thanks to finite stack space the loop was finite.

**Comment by nigoroll** [comment]
A revert of fe96d9828b263c903adfd7d4a90e2d7a9abc20cf does not change the overall appearance of the stack trace

**Comment by bsdphk** [comment]
I have attempted more sane handling of reentrant panics.

(That obviously does not solve the underlying issue)
