### ISSUE TITLE
Issues building VMODs with master and no $ABI or $ABI vrt

### ISSUE THREAD

**Issue by fgsch** [varnishcache/varnish-cache#3821]
Trying to build a vmod with revision 2e9133647a28b03d2c423371501cdb3a1036f0ac fails with:

```
/usr/local/bin/python3.9 /opt/varnish/share/varnish/vmodtool.py ../src/vmod.vcc
Traceback (most recent call last):
  File "/opt/varnish/share/varnish/vmodtool.py", line 1243, in <module>
    runmain(i_vcc, opts.rstdir, opts.output)
  File "/opt/varnish/share/varnish/vmodtool.py", line 1208, in runmain
    v.mkcfile()
  File "/opt/varnish/share/varnish/vmodtool.py", line 1189, in mkcfile
    self.json(fo, fnx)
  File "/opt/varnish/share/varnish/vmodtool.py", line 1120, in json
    fo.write('\t    STRINGIFY(%s) ", "\n' % self.vrt_major)
AttributeError: 'vcc' object has no attribute 'vrt_major'
make[1]: *** [vcc_if.c] Error 1
make: *** [check-recursive] Error 1
```

if `$ABI` is missing. 

If `$ABI` is set to `vrt` it builds but the `VRT_MAJOR_VERSION` and `VRT_MINOR_VERSION` are not correctly expanded and loading the VMOD fails with:

```
**** v1    CLI RX|VMOD <vmod>: bad metadata
**** v1    CLI RX|\t(Unrecognized value)
**** v1    CLI RX|\tFile name: /Users/fgsch/foss/<vmod>/src/.libs/libvmod_<vmod>.so
```

Running `strings` in the VMOD shows:

```
["$VMOD", "1.0", "<vmod>", "Vmod_vmod_<vmod>_Func", "..." , "Varnish trunk ...", VRT_MAJOR_VERSION, VRT_MINOR_VERSION  ],
...
```

Instead of the major and minor VRT versions.

**Comment by bsdphk** [comment]
fixed in fcb823b02cd89595
